Updated isolated workloads formatting and info for local deployment
loft-sh/vcluster-docs pull request #187
Opened 2024-07-10 13:57 UTC by ThomasK33

2024-07-10 23:31 UTC, deniseschannon requested changes
The grammar is honestly not great in this whole page, but I pointed out the obvious issues of how we want to present information to our users.

2024-07-10 23:31 UTC, deniseschannon commented on vcluster/deploy/topologies/isolated-workloads.mdx
> +You can adjust isolation settings through helm values (vcluster.yaml). To configure
We want to move away from referencing and calling `helm values` even if that is technically what it is and call it only `vcluster.yaml. 

I'd update this to:

Adjust your isolation settings through the `vcluster.yaml` of the vCluster:

2024-07-10 23:31 UTC, deniseschannon commented on vcluster/deploy/topologies/isolated-workloads.mdx
> +the host cluster through their cluster ips. This can be sometimes beneficial if
Capitalize `IPs`

2024-07-10 23:31 UTC, deniseschannon commented on vcluster/deploy/topologies/isolated-workloads.mdx
> +share services between vClusters. However, you often want to isolate namespaces
update from `vClusters` to `virtual clusters`. We should never pluralize vCluster.

2024-07-10 23:31 UTC, deniseschannon commented on vcluster/deploy/topologies/isolated-workloads.mdx
> +following option:
"enabling the following option in your `vcluster.yaml`:"

2024-07-10 23:31 UTC, deniseschannon commented on vcluster/deploy/topologies/isolated-workloads.mdx
> +can be enabled on demand. To enable you can use:
Replace `To enable you can use:` to `To enable this option, enable the configuration in the vcluster.yaml:`

2024-07-11 10:30 UTC, ThomasK33 commented
@deniseschannon I can have it run through Grammarly if that helps.

This PR mainly includes lint fixes from [markdownlint](https://github.com/DavidAnson/markdownlint) and that one added info box for a local setup.

I updated the PR with your fixes.

2024-07-11 13:56 UTC, deniseschannon commented
@ThomasK33 There are still notes about how it could be a security risk in the last paragraph that I would like updated. Since this is a default option, why would we have a default option that has security risks? Therefore I want it changed to not include the idea of security risks could exist.

2024-07-14 23:34 UTC, merged