ENG-4153 | Document setting up GKE Workload Identity/EKS Pod Identity
loft-sh/vcluster-docs pull request #200
Opened 2024-07-17 10:29 UTC by janekbaraniewski

2024-07-23 17:00 UTC, heiko-braun commented
Thanks @janekbaraniewski this escaped my attention. I will take a look at it tomorrow

2024-07-24 10:06 UTC, heiko-braun commented
@janekbaraniewski why did we drop the terraform module from the docs?

2024-07-30 12:59 UTC, zerbitx submitted a review, later dismissed
LGTM

2024-07-30 17:36 UTC, deniseschannon requested changes
1.  We want to move this from the platform docs to the vCluster docs as most people will search for this in the vcluster docs. We also want to group both pages under Pod Identity and then have EKS and GKE.
   1.  EKS: Integrations -> Identity -> EKS
   2.  GKE: Integrations -> Identify -> GKE
2.  Since you need the platform, these pages should be labeled as pro, so it shows up in the side bar: Example front matter that you'll need: https://github.com/loft-sh/vcluster-docs/blob/main/vcluster/configure/vcluster-yaml/experimental/isolated-control-plane.mdx?plain=1#L5
3.  Since it will be under vCluster now instead of the platform, we should remove the vCluster Platform running as a pre-req and instead it becomes one of the steps of the guide. In that step, it should refer to the install vCluster Platform docs.
4.  Can the formats of the two guide match and follow the EKS style for the heading? So don't have headings that say Step 1 but instead 1.
5.  For the steps that are deploying the vcluster, can you either use the partial from the basics page as you can deploy vCluster however you want? https://github.com/loft-sh/vcluster-docs/blob/main/vcluster/deploy/basics.mdx?plain=1#L180

2024-08-02 14:05 UTC, deniseschannon commented
Can you run it through spell check real quick? I found a spelling error, but it might be easier to have you run it through spelling rather than me comment on each one.

2024-08-05 07:40 UTC, janekbaraniewski commented on vcluster/integrations/pod-identity/eks-pod-identity.mdx
> +vcluster connect ${VCLUSTER_NAME}
`VCLUSTER_NAME` is set to `my-vcluster` in previous step

2024-08-06 04:45 UTC, deniseschannon requested changes
Nit: if we declare the env vars with all caps, can we reference them with all caps as well through out the docs?

2024-08-06 12:53 UTC, deniseschannon approved these changes

2024-08-06 12:53 UTC, merged