Adding changed to yaml for embedded etcd
loft-sh/vcluster-docs pull request #238
Opened 2024-08-13 20:55 UTC by sowmyav27

2024-08-13 21:16 UTC, rmweir commented on vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded.mdx
> +        migrateFromDeployedEtcd: false #default value
I think if this must be placed under "You can migrate from an external etcd instance to the embedded one by configuring `migrateFromDeployedEtcd: true`." Then this should be true. Another option would be to keep this false and then change the line above to be a note either below or above so its clearly a suggestion in addition to what is being presented generally.

2024-08-14 20:13 UTC, zerbitx approved these changes

2024-08-15 00:42 UTC, deniseschannon requested changes

2024-08-15 00:42 UTC, deniseschannon commented on vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded.mdx
> +You can migrate from an external etcd instance to the embedded one by configuring `migrateFromDeployedEtcd: true` as shown below. However, by default, `enabled` is set to `false`, and `migrateFromDep
I'm not sure if you need any additional information. Did you test this out? 

But otherise, I'd change it to:

```
You can migrate from an external etcd instance to the embedded one by configuring `migrateFromDeployedEtcd: true`. You will also need to enable the embedded etcd in order to enable the migration. 
```

2024-08-21 07:15 UTC, merged