Update explaining syncing and bi-directional syncing
loft-sh/vcluster-docs pull request #329
Opened 2024-10-22 03:26 UTC by deniseschannon

2024-10-22 22:00 UTC, sowmyav27 requested changes

2024-10-22 22:12 UTC, deniseschannon commented on vcluster/_fragments/how-does-syncing-work.mdx
> +As soon as a resource is copied by vCluster, the syncer starts watching for changes to the resource on either side. When the resource
The original sentence made it imply that bi-directional syncing was happening, which is not the case, but I'll try to clear it up a bit.

2024-10-22 22:14 UTC, deniseschannon commented on vcluster/_fragments/how-does-syncing-work.mdx
> +Any changes to the resource in the virtual cluster are automatically applied to the resource in the host cluster.
No, changes in the host cluster are not automatically applied back to the resource in the virtual cluster. It's only the specific fields, which I've put in the parts of syncing when we talk about resources being synced to/from Host

2024-10-25 21:53 UTC, deniseschannon commented on vcluster/_fragments/how-does-syncing-work.mdx
> +permissions.
I didn't realize this was also used in the architecture page. 

I'll review the duplicate content in the architecture page vs the "how does syncing work" to see if we want to reuse the fragment in both places or link.

2024-10-25 21:54 UTC, deniseschannon commented on vcluster/_fragments/how-does-syncing-work.mdx
> +is updated in the virtual cluster, the syncer copies those changes in host cluster.
Good point, I'll write/clarify this. 

Basically, changes in the host cluster are overwritten whenever the virtual cluster resource is synced to the host cluster unless it's a bi-directional field. 

I'll need to check how often we sync.

2024-10-25 21:57 UTC, deniseschannon commented on vcluster/_fragments/sync-from-host-resources.mdx
> +There are a couple of labels that are created on the host cluster by vCluster that never get synced to the virtual cluster resource. These labels are:
I need to clarify on what happens as it wasn't clear with the original docs. 

I know from virtual -> host, we create a set of new labels on the host cluster, that don't exist on the virtual cluster. 

On host -> virtual, I am not sure what labels we add in and when. I'll need to clarify and check.

2024-11-06 02:15 UTC, merged